# Generated by Django 5.2.5 on 2025-08-22 01:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('disposition_type', models.CharField(choices=[('contact', 'Contact Made'), ('no_contact', 'No Contact'), ('callback', 'Callback'), ('system', 'System'), ('compliance', 'Compliance')], default='contact', max_length=20)),
                ('is_sale', models.BooleanField(default=False, help_text='Mark as successful sale')),
                ('is_contact', models.BooleanField(default=True, help_text='Count as contact made')),
                ('requires_callback', models.BooleanField(default=False)),
                ('allows_retry', models.BooleanField(default=True, help_text='Allow lead to be called again')),
                ('remove_from_campaign', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaigns', models.ManyToManyField(blank=True, help_text='Campaigns where this disposition is available', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disposition_codes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alt_phone', models.CharField(blank=True, help_text='Alternative phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='US', max_length=50)),
                ('list_id', models.CharField(blank=True, help_text='Source list identifier', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('called', 'Called'), ('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('disconnected', 'Disconnected'), ('callback', 'Callback'), ('dnc', 'Do Not Call'), ('completed', 'Completed'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate')], db_index=True, default='new', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Lowest')], db_index=True, default=3)),
                ('attempts', models.IntegerField(db_index=True, default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_call_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_call_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timezone', models.CharField(default='UTC', help_text="Lead's timezone", max_length=50)),
                ('best_call_time_start', models.TimeField(blank=True, null=True)),
                ('best_call_time_end', models.TimeField(blank=True, null=True)),
                ('do_not_call_after', models.DateTimeField(blank=True, null=True)),
                ('callback_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('callback_notes', models.TextField(blank=True)),
                ('lead_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lead_source', models.CharField(blank=True, max_length=100)),
                ('lead_type', models.CharField(blank=True, max_length=50)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Additional custom fields as JSON')),
                ('is_dnc', models.BooleanField(db_index=True, default=False)),
                ('dnc_reason', models.CharField(blank=True, max_length=100)),
                ('consent_to_call', models.BooleanField(default=True)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('source_file', models.CharField(blank=True, max_length=200)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('callback_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_leads', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='campaigns.campaign')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_duration', models.DurationField(blank=True, null=True)),
                ('talk_time', models.DurationField(blank=True, help_text='Actual talk time with customer', null=True)),
                ('notes', models.TextField(blank=True)),
                ('callback_datetime', models.DateTimeField(blank=True, null=True)),
                ('callback_notes', models.TextField(blank=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_interest', models.CharField(blank=True, max_length=100)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('phone_dialed', models.CharField(blank=True, max_length=17)),
                ('caller_id_used', models.CharField(blank=True, max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wrap_up_time', models.DurationField(blank=True, help_text='Time spent in wrap-up', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions_made', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='campaigns.campaign')),
                ('disposition_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.dispositioncode')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='leads.lead')),
            ],
            options={
                'db_table': 'dispositions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('filename', models.CharField(max_length=200)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('duplicates_found', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='campaigns.campaign')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_import_batches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private note visible only to agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['campaign', 'status'], name='leads_campaig_4d51e0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_phone_13acb4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_call_at'], name='leads_next_ca_4acfb3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['callback_datetime'], name='leads_callbac_f58d57_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['attempts', 'status'], name='leads_attempt_19c42f_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['lead', 'created_at'], name='disposition_lead_id_655e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['campaign', 'created_at'], name='disposition_campaig_09c35c_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['agent', 'created_at'], name='disposition_agent_i_2c9682_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['disposition_code'], name='disposition_disposi_232674_idx'),
        ),
    ]
