# Generated by Django 4.2.16 on 2025-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='recycle_count',
            field=models.IntegerField(default=0, help_text='Number of times this lead has been recycled'),
        ),
    ]
