# Generated by Django 4.2.16 on 2025-08-23 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('disposition_code', models.CharField(db_index=True, help_text='Standardized disposition code', max_length=50)),
                ('disposition_name', models.CharField(help_text='Human-readable disposition name', max_length=100)),
                ('category', models.CharField(choices=[('contact', 'Contact Made'), ('no_contact', 'No Contact'), ('callback', 'Callback Required'), ('dnc', 'Do Not Call'), ('sale', 'Sale/Success'), ('system', 'System Related')], db_index=True, max_length=20)),
                ('disposition_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wrap_up_time', models.DateTimeField(blank=True, help_text='Time when wrap-up was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Agent notes about the call')),
                ('is_final', models.BooleanField(default=True, help_text='Whether this is a final disposition')),
                ('requires_followup', models.BooleanField(default=False)),
                ('schedule_callback', models.BooleanField(default=False)),
                ('callback_date', models.DateField(blank=True, null=True)),
                ('callback_time', models.TimeField(blank=True, null=True)),
                ('callback_type', models.CharField(blank=True, choices=[('specific_time', 'Specific Time'), ('anytime', 'Anytime'), ('best_time', 'Best Time to Call'), ('appointment', 'Scheduled Appointment')], max_length=20)),
                ('callback_notes', models.TextField(blank=True)),
                ('callback_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('best_time_start', models.TimeField(blank=True, null=True)),
                ('best_time_end', models.TimeField(blank=True, null=True)),
                ('best_days', models.CharField(blank=True, help_text='Preferred days of week', max_length=20)),
                ('timezone_preference', models.CharField(blank=True, max_length=50)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('products_sold', models.JSONField(blank=True, help_text='List of products/services sold', null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_score', models.IntegerField(blank=True, help_text='Call quality score 1-10', null=True)),
                ('compliance_flags', models.JSONField(blank=True, help_text='Any compliance issues noted', null=True)),
                ('requires_supervisor_review', models.BooleanField(default=False)),
                ('supervisor_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether disposition data is valid')),
                ('validation_errors', models.JSONField(blank=True, help_text='Any validation errors', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_dispositions', to=settings.AUTH_USER_MODEL)),
                ('call_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='calls.calltask')),
                ('cdr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposition', to='calls.calldetailrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dispositions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_dispositions',
                'ordering': ['-disposition_time'],
                'indexes': [models.Index(fields=['disposition_code'], name='call_dispos_disposi_038302_idx'), models.Index(fields=['category', 'disposition_time'], name='call_dispos_categor_e25354_idx'), models.Index(fields=['agent', 'disposition_time'], name='call_dispos_agent_i_c628b5_idx'), models.Index(fields=['schedule_callback', 'callback_date'], name='call_dispos_schedul_c0b314_idx'), models.Index(fields=['requires_followup'], name='call_dispos_require_cd8c24_idx'), models.Index(fields=['is_final'], name='call_dispos_is_fina_8a08e2_idx'), models.Index(fields=['requires_supervisor_review'], name='call_dispos_require_00b471_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(check=models.Q(('schedule_callback', False), models.Q(('schedule_callback', True), ('callback_date__isnull', False)), _connector='OR'), name='callback_date_required_when_scheduled'),
        ),
    ]
