# Generated by Django 4.2.16 on 2025-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='exclude_dnc_from_recycling',
            field=models.BooleanField(default=True, help_text='Exclude DNC leads from recycling'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_recycle_attempts',
            field=models.IntegerField(default=2, help_text='Maximum number of times a lead can be recycled'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recycle_busy_days',
            field=models.IntegerField(default=1, help_text="Days after which 'busy' leads are recycled"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recycle_disconnected_days',
            field=models.IntegerField(default=30, help_text="Days after which 'disconnected' leads are recycled"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recycle_no_answer_days',
            field=models.IntegerField(default=7, help_text="Days after which 'no answer' leads are recycled"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recycle_only_business_hours',
            field=models.BooleanField(default=True, help_text='Only recycle leads during campaign business hours'),
        ),
    ]
